### ISSUE TITLE
Lower Notion Update Frequency to Max 4hrs per Page

### ISSUE THREAD

**Issue by laprasdev** [BloomGameStudio/NotionDiscordIntegration#10]
Right now, high frequency minor updates procure the notion API, and the discord bot gets spammed.

For example, if someone types a few passages, it will likely send updates every few sentences.

Adding a time limit to not repeat an update for 4 hours (or alternatively, sending an update after a 'cool off' period) will be a clean way to remove this noise and make the updates more usale.

**Comment by Sarahtonein** [comment]
created branch and commited here:

https://github.com/BloomGameStudio/NotionDiscordIntegration/commit/1073697edda9a7101b4d40f185a730a98accf9d3
