### ISSUE TITLE
Aggregate update timing

### ISSUE THREAD

**Issue by Sarahtonein** [BloomGameStudio/NotionDiscordIntegration#18]
Currently if the bot is restarted it will restart the weekly delay that posts aggregate updates to Discord.

This should be fixed. Because, if the bot is restarted on the 6th day, and then restarted 6 days later a second time, there will be a total of 19 days delay before an update is posted.

**Comment by Balugrizzly** [comment]
Can this be closed?

**Comment by Sarahtonein** [comment]
> Can this be closed?

Yup this can be closed
